import tkinter
from tkinter import*
TOP = Tk()
top = tkinter.Tk()
B = tkinter.Button(top,text= "Hello World")
Menubtn = tkinter.Menubutton(top,text= "Menu Button")
M = tkinter.Radiobutton(top,text="male")
F = tkinter.Radiobutton(top,text="female")
T = tkinter.Text(top,background="teal",height="10",width="100")
Lb1 = Listbox(TOP)
Lb1.insert(1,"Python")
Lb1.insert(2,"Hadoop")
Lb1.insert(3,"Java")
Lb1.insert(4,"Spark")
Lb1.insert(5,"Scala")
B.pack()
Menubtn.pack()
F.pack()
M.pack()
T.pack()
Lb1.pack()
# top.mainloop()
TOP.mainloop()
